- name: Restore Dependencies
      run: dotnet restore IDCardStudio.csproj

    - name: Build Project (Release x64)
      run: dotnet build IDCardStudio.csproj -c Release -r win-x64 --no-restore

    - name: Publish Self-Contained Executable
      run: |
        dotnet publish IDCardStudio.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:SelfContained=true --output ./publish
